"""Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""from itertools import takewhile

def fibs():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a+b

ans = sum(n for n in takewhile(lambda x: x < 4000000, fibs()) if n%2 == 0)
print(ans)
