"""Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The
first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum
and difference are pentagonal and D = |Pk - Pj| is minimised; what is
the value of D?

"""
from itertools import product
from math import sqrt
LIMIT = 2500

def pentagonal(n):
    return n*(3*n - 1) // 2

pentagonals = [pentagonal(n) for n in range(1, LIMIT)]

def isPentagonal(p_n):
    return ((1/2 + sqrt(1/4 + 6*p_n)) / 3) % 1 == 0

def D(p1, p2): return abs(p1 - p2)

pentagonalPairs = sorted(((pentagonals[k], pentagonals[j])
                          for k in range(LIMIT-1)
                          for j in range(k)),
                         key=lambda pair: D(*pair))

ans = D(*next(filter(lambda pair: isPentagonal(sum(pair)) and isPentagonal(D(*pair)),
                     pentagonalPairs)))

print(ans)
