"""Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:

Triangle   Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal   Pn=n(3n-1)/2   1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n-1)   1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""
from itertools import count
from math import sqrt

def isPentagonal(p_n):
    return ((1/2 + sqrt(1/4 + 6*p_n)) / 3) % 1 == 0

def hexagonal(n): return n*(2*n - 1)

ans = next(filter(lambda n: isPentagonal(n) and n > 40755, map(hexagonal, count(1))))

print(ans)

